### ISSUE TITLE
noarch/cdat_info-8.2.1.rc1-py_0.tar.bz2 should not be marked as 'main'

### ISSUE THREAD

**Issue by muryanto1** [conda-forge/cdat_info-feedstock#22]
Issue:  due to https://github.com/conda-forge/cdat_info-feedstock/pull/21, noarch/cdat_info-8.2.1.rc1-py_0.tar.bz2 mistakenly got uploaded to conda-forge and labeled 'main'.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xylar** [comment]
closed via https://github.com/conda-forge/admin-requests/pull/90
